### ISSUE TITLE
The query result is not the same as the inserted result

### ISSUE THREAD

**Issue by hetao92** [vesoft-inc/nebula-graph#1318] opened 2021-08-16 10:07 UTC
schema vid_type FIXED_STRING(64)

create tag code1(data_source string,item_id string,item_name string, T41_1 string,T41_2 string,T41_3 string,T41_4 datetime,T41_5 datetime)

insert vertex code1(data_source,item_id,item_name, T41_1,T41_2,T41_3,T41_4,T41_5) VALUES 't41_000001':('0','000001','00国债01','000001','00国债01','',date('2021-03-10T10:40:23.323323323'), date('2021-03-10T10:40:23.323323323'))

match (v:code1) where id(v) =='t41_000001' return v

item_id result is different, and why has '\u0000' in result

![image](https://user-images.githubusercontent.com/18328704/129547157-f00737cf-a0c2-4915-baad-bd5cab78c7ab.png)

**Comment by Shylock-Hg** [comment] 2021-08-17 03:27
Caused by the storage write date type to datetime type.

**Comment by Shylock-Hg** [comment] 2021-08-17 03:29
The date parse will fixed in https://github.com/vesoft-inc/nebula-graph/pull/984

**Closed** 2021-08-17 11:25 UTC
Labels: bug
