### ISSUE TITLE
Mixing AND and OR in WHERE in LOOKUP causes strange errors

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#1121] opened 2021-06-09 07:20 UTC
At first I ran the following statement:

LOOKUP ON player WHERE player.age < 30 AND player.name == "Yao Ming" \
        OR (player.name == "Yao Ming" OR player.name == "Tim Duncan") \
        YIELD player.name, player.age;

The result is as follows:

![image](https://user-images.githubusercontent.com/69501902/121310389-e8232880-c935-11eb-8432-0c2110f092e2.png)

Then I tried a shorter statement:

LOOKUP ON player WHERE player.age < 30 AND player.name == "Yao Ming" OR player.name == "Tim Duncan" YIELD player.name, player.age;

The result is as follows:

![image](https://user-images.githubusercontent.com/69501902/121310683-33d5d200-c936-11eb-9192-2df38a054e4b.png)

The results look different. Please take a look at them.

**Comment by bright-starry-sky** [comment] 2021-06-09 07:48
This expression is not supported yet，but my error message is different from yours, please verify it. 
```
CREATE TAG player(c_int int, c_string string, c_fixed_string_256 fixed_string(256), c_fixed_string_257 fixed_string(257));
CREATE TAG INDEX idx_1 on player(c_int, c_string(256), c_fixed_string_256)
INSERT VERTEX player(c_int, c_string, c_fixed_string_256, c_fixed_string_257) VALUES "1":(1, "string", "fixed_string_256", "fixed_string_257")
LOOKUP ON player WHERE player.c_int < 2 AND player.c_string == "string" OR player.c_string == "aaa" yield player.c_int , player.c_string
```

![image](https://user-images.githubusercontent.com/56461666/121314133-a5634f80-c939-11eb-9b31-b28081ba4338.png)

**Comment by bright-starry-sky** [comment] 2021-06-10 02:54
I think we can close this issue. As for the problem that the error message is too long, it is better to open a new issue.

**Comment by randomJoe211** [comment] 2021-06-10 03:29
Why should we open a new issue only because the error message is too long?
I don't get it, but as long as this bug can be solved, I'm OK. And please attach the link to the new issue here.
Thank you!

**Comment by HarrisChu** [comment] 2021-06-15 08:55
two bugs:
1. conditions are inconsistent in `go` and lookup` statements.

```
(root@nebula) [nba]>  go from 'Tony Parker' over like where like.likeness>90 or (like.likeness > 80 and like.likeness < 100)
+---------------------+
| like._dst           |
+---------------------+
| "LaMarcus Aldridge" |
+---------------------+
| "Manu Ginobili"     |
+---------------------+
| "Tim Duncan"        |
+---------------------+
Got 3 rows (time spent 2593/9499 us)

Tue, 15 Jun 2021 16:50:50 CST

(root@nebula) [nba]> LOOKUP ON player where player.age > 10 or ( player.age > 5 and player.age < 20)
[ERROR (-8)]: NotSupported: Condition not support yet : %sRange scan for bool type is illegalData type error of field : %sIndex Scan plan node errorNo index was foundFilter not support yet : %sNo valid index foundPlan node dependencies errorOptimizer erN6nebula3opt13IndexScanRuleE�ʔp9/�3/�9/c

Tue, 15 Jun 2021 16:51:38 CST
```

2.  unreadable error message.

**Comment by bright-starry-sky** [comment] 2021-06-16 04:40
I don't know why you are comparing `GO` to `LOOKUP`, they have different execution logic and limitations. `Lookup` has explicitly told you that it does not support this condition, this error message is expected, not a bug. I think what you really need to explore is the error message, not the unsupported filter.

**Comment by bright-starry-sky** [comment] 2021-06-16 04:41
Close this issue.

**Closed by bright-starry-sky** 2021-06-16 04:41 UTC
Labels: bug, med-pri
